### PR TITLE
feat: rename package name

### PR DESCRIPTION
**Pull request by leoner**

### CODE REVIEW

**Comment by fengmk2** [comment]
commit author 改一下

image

**Comment by fengmk2** [comment]
readme 也改改 https://github.com/node-modules/hessian.js/tree/1.x#install

**Comment by fengmk2** [comment]
我手动合并一下吧

**Comment by leoner** [comment]
@fengmk2 好了. 自动合并有问题?

**Comment by fengmk2** [comment]
1.2.0

**Comment by leoner** [comment]
copy it.

**Pull request merged**
